Repository Team-Tokkit/Tokkit-Client-Admin, pull requests merged in 2025-05, with the labels that each got.

#3 Feat: 관리자 로그인 페이지 구현
  app/login/components/LoginCard.tsx
  app/login/components/LoginForm.tsx
  app/login/page.tsx
  package-lock.json
  package.json
Labels: FEAT

#4 Refactor: 관리자 페이지 컴포넌트 분리
  app/auth/page.tsx
  app/dashboard/page.tsx
  app/layout.tsx
  app/login/components/LoginForm.tsx
  app/logs/page.tsx
  app/merchant/page.tsx
  app/notice/page.tsx
  app/page.tsx
  app/payment/page.tsx
  app/user/page.tsx
  components/layout/Header.tsx
  components/layout/LayoutWrapper.tsx
  components/layout/MainLayout.tsx
  components/layout/Sidebar.tsx
Labels: REFACTOR

#8 Feat: 관리자 페이지 (API 요청 로그)
  app/api-logs/components/ApiLogChart.tsx
  app/api-logs/components/ApiLogDetail.tsx
  app/api-logs/components/CustomCalendar.tsx
  app/api-logs/components/CustomPagination.tsx
  app/api-logs/page.tsx
  app/logs/page.tsx
  app/page.tsx
  app/system-logs/page.tsx
  app/voucher/issue/loading.tsx
  app/voucher/issue/page.tsx
  app/voucher/loading.tsx
  app/voucher/page.tsx
  components/auth-content.tsx
  components/layout/Sidebar.tsx
  components/payment-content.tsx
  components/system-log-content.tsx
  data/mockLogs.ts
  lib/api.ts
  lib/api/api-logs.ts
  lib/getApiUrl.ts
  package-lock.json
  package.json
Labels: FEAT

#10 Feat: API 요청 로그, 사용자 관리 페이지
  app/api-logs/components/ApiLogDetail.tsx
  app/api-logs/components/CustomCalendar.tsx
  app/api-logs/page.tsx
  app/user/components/DeleteModal.tsx
  app/user/components/ManageBox.tsx
  app/user/components/PinChangeModal.tsx
  app/user/components/UserDetailModal.tsx
  app/user/page.tsx
  components/common/DateRangePicker.tsx
  components/common/List.tsx
  components/common/Pagination.tsx
  package-lock.json
  package.json
Labels: FEAT

#12 Feat: 로그 페이지 구현
  app/api-logs/api/api-logs.ts
  app/api-logs/components/ApiLogChart.tsx
  app/api-logs/page.tsx
  app/system-logs/api/system-logs.ts
  app/system-logs/components/SystemLogDetail.tsx
  app/system-logs/page.tsx
  app/user/api/user.ts
  app/user/components/UserDetailModal.tsx
  app/user/page.tsx
Labels: FEAT

#15 ✨ Feat/#13 transaction 대시보드 구현 완료
  app/payment/page.tsx
  app/transaction/api/transaction-api.ts
  app/transaction/componets/TransactionDetailDialog.tsx
  app/transaction/page.tsx
  components/layout/Sidebar.tsx
Labels: FEAT

#18 Refactor: 로그 관련 페이지 최종 수정
  app/auth/api/auth-logs.ts
  app/auth/components/AuthLogDetail.tsx
  app/auth/page.tsx
  app/dashboard/api/dashboard.ts
  app/dashboard/components/Overview.tsx
  app/dashboard/components/Stats.tsx
  app/dashboard/components/SystemStatus.tsx
  app/dashboard/page.tsx
  app/error-logs/api/error-logs.ts
  app/error-logs/components/ErrorLogDetail.tsx
  app/error-logs/page.tsx
  app/system-logs/components/SystemLogDetail.tsx
  app/system-logs/page.tsx
  app/user/api/user.ts
  app/user/components/DeleteModal.tsx
  app/user/components/ManageBox.tsx
  app/user/components/PinChangeModal.tsx
  app/user/components/UserDetail.tsx
  app/user/page.tsx
  components/common/Page-Header.tsx
  components/layout/Sidebar.tsx
  lib/statusStyle.ts
Labels: REFACTOR

#20 Refactor: 사용자 관리 상세 및 수정 드롭박스 추가
  app/user/components/UserDetail.tsx
  app/user/components/UserEdit.tsx
  app/user/page.tsx
  components/common/DropBox.tsx
Labels: REFACTOR

#22 Feat: 공지사항 페이지 구현
  app/notice/api/notice.ts
  app/notice/components/NoticeDelete.tsx
  app/notice/components/NoticeDetail.tsx
  app/notice/components/NoticeEdit.tsx
  app/notice/page.tsx
  app/user/page.tsx
  components/common/DropBox.tsx
Labels: FEAT

#25 ✨ Feat: [ADMIN] Merchant 대시보드 추가
  app/merchant/api/merchant.ts
  app/merchant/components/MerchantEditDialog.tsx
  app/merchant/components/MerchantViewDialog.tsx
  app/merchant/handlers/useFetchMerchantData.ts
  app/merchant/handlers/useMerchantActions.ts
  app/merchant/page.tsx
  components/common/Dropbox.tsx
Labels: REFACTOR, FEAT

#28 Refactor: 공지사항 삭제 기능 수정
  app/api-logs/page.tsx
  app/notice/api/notice.ts
  app/notice/components/NoticeDelete.tsx
  app/notice/components/NoticeDetail.tsx
  app/notice/page.tsx
Labels: REFACTOR

#33 ✨ Feat: unified log dashboard 추가
  app/error-logs/components/ErrorLogDetail.tsx
  app/unified-logs/api/unified-logs.ts
  app/unified-logs/components/CustomDateRangePicker.tsx
  app/unified-logs/components/UnifiedLogDetailDialog.tsx
  app/unified-logs/page.tsx
  app/unified-logs/types/log.ts
  app/user/page.tsx
  components/common/DropBox.tsx
  components/common/Dropbox.tsx
  components/layout/Sidebar.tsx
Labels: FEAT

#35 Chore: 관리자 cypress
  app/merchant/page.tsx
  app/notice/components/NoticeDelete.tsx
  app/notice/components/NoticeDetail.tsx
  app/notice/components/NoticeEdit.tsx
  app/notice/page.tsx
  app/user/page.tsx
  app/voucher/components/CreateForm.tsx
  app/voucher/components/UpdateModal.tsx
  app/voucher/components/VoucherCreatePage.tsx
  app/voucher/components/VoucherDetailModal.tsx
  app/voucher/components/VoucherList.tsx
  app/voucher/create/page.tsx
  app/voucher/page.tsx
  components/common/DropBox.tsx
  components/common/Pagination.tsx
  components/common/drop-box.tsx
  cypress.config.ts
  cypress/e2e/notice.cy.ts
  cypress/e2e/spec.cy.ts
  cypress/e2e/voucher-delete.cy.ts
  cypress/e2e/voucher.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
Labels: TEST
