Repository Team-Tokkit/Tokkit-Client-Admin, pull requests merged in 2025-06, with the labels that each got.

#37 Feat: 관리자 로그인, 로그아웃 프론트엔드 구현 및 API 연동
  app/api-logs/api/api-logs.ts
  app/auth/api/auth-logs.ts
  app/error-logs/api/error-logs.ts
  app/layout.tsx
  app/login/api/authApi.ts
  app/login/components/LoginForm.tsx
  app/login/page.tsx
  app/merchant/api/merchant.ts
  app/notice/api/notice.ts
  app/page.tsx
  app/transaction/api/transaction-api.ts
  app/unified-logs/api/unified-logs.ts
  app/user/api/user.ts
  app/voucher/lib/api.ts
  components/auth-content.tsx
  components/auth-provider.tsx
  components/dashboard-nav.tsx
  components/delete-confirm-dialog.tsx
  components/layout/LayoutWrapper.tsx
  components/merchant-content.tsx
  components/notice-content.tsx
  components/notice-detail-dialog.tsx
  components/notice-edit-dialog.tsx
  components/payment-content.tsx
  components/system-log-content.tsx
  lib/apiClient.ts
  lib/parseJwt.ts
  middleware.ts
  package-lock.json
  package.json
  public/favicon.ico
  public/login-background.png
Labels: REFACTOR, CHORE, FEAT

#38 [DEPLOY] v1.0.1
  app/api-logs/api/api-logs.ts
  app/auth/api/auth-logs.ts
  app/error-logs/api/error-logs.ts
  app/layout.tsx
  app/login/api/authApi.ts
  app/login/components/LoginForm.tsx
  app/merchant/api/merchant.ts
  app/merchant/page.tsx
  app/notice/api/notice.ts
  app/notice/components/NoticeDelete.tsx
  app/notice/components/NoticeDetail.tsx
  app/notice/components/NoticeEdit.tsx
  app/notice/page.tsx
  app/page.tsx
  app/transaction/api/transaction-api.ts
  app/unified-logs/api/unified-logs.ts
  app/user/api/user.ts
  app/user/page.tsx
  app/voucher/components/CreateForm.tsx
  app/voucher/components/UpdateModal.tsx
  app/voucher/components/VoucherCreatePage.tsx
  app/voucher/components/VoucherDetailModal.tsx
  app/voucher/components/VoucherList.tsx
  app/voucher/create/page.tsx
  app/voucher/lib/api.ts
  app/voucher/page.tsx
  components/auth-content.tsx
  components/auth-provider.tsx
  components/common/Pagination.tsx
  components/common/drop-box.tsx
  components/dashboard-nav.tsx
  components/delete-confirm-dialog.tsx
  components/layout/LayoutWrapper.tsx
  components/merchant-content.tsx
  components/notice-content.tsx
  components/notice-detail-dialog.tsx
  components/notice-edit-dialog.tsx
  components/payment-content.tsx
  components/system-log-content.tsx
  cypress.config.ts
  cypress/e2e/notice.cy.ts
  cypress/e2e/spec.cy.ts
  cypress/e2e/voucher-delete.cy.ts
  cypress/e2e/voucher.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  lib/apiClient.ts
  lib/parseJwt.ts
  middleware.ts
  package-lock.json
  package.json
  public/favicon.ico
  public/login-background.png
Labels: RELEASE

#46 [DEPLOY] v1.0.3
  lib/apiClient.ts
  middleware.ts
Labels: RELEASE

#51 :but: Fix: api logs bar
  .github/PULL_REQUEST_TEMPLATE.md
  app/api-logs/page.tsx
Labels: FIX

#52 :but: Fix: api logs bar (#51)
  .github/PULL_REQUEST_TEMPLATE.md
  app/api-logs/page.tsx
Labels: FIX
